USE UNIVER
/*1*/
--Разработать сценарий, формирующий список дисциплин на кафедре ИСиТ. 

DECLARE @ONE NVARCHAR(20), @ALL NVARCHAR(300) = '';
DECLARE LINES CURSOR FOR SELECT SUBJECT FROM SUBJECT
OPEN LINES
FETCH LINES INTO @ONE
PRINT 'Предметы:'
WHILE @@FETCH_STATUS = 0
BEGIN

    SET @ALL = RTRIM(@ONE) + ', ' + @ALL 
 
    FETCH LINES INTO @ONE
END

PRINT RTRIM(@ALL) + '.'
CLOSE LINES

/*2*/
---GLOBAL
DECLARE @IDSTUDENT INT, @IDGROUP INT, @NAME NVARCHAR(100), @BDAY DATE
DECLARE global_cursor CURSOR FOR
SELECT IDSTUDENT, IDGROUP, NAME, BDAY
FROM STUDENT
OPEN global_cursor

FETCH NEXT FROM global_cursor INTO @IDSTUDENT, @IDGROUP, @NAME, @BDAY

PRINT 'Глобальный курсор:'
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT 'ID: ' + CAST(@IDSTUDENT AS NVARCHAR(10)) + ', Группа: ' + CAST(@IDGROUP AS NVARCHAR(10)) + ', Имя: ' + @NAME + ', День рождения: ' + CONVERT(NVARCHAR(10), @BDAY, 104)
    FETCH NEXT FROM global_cursor INTO @IDSTUDENT, @IDGROUP, @NAME, @BDAY
END

CLOSE global_cursor
DEALLOCATE global_cursor

--LOCAL
DECLARE local_cursor CURSOR FOR
SELECT IDSTUDENT, IDGROUP, NAME, BDAY
FROM STUDENT
WHERE IDGROUP = 2
OPEN local_cursor
DECLARE @IDSTUDENT_LOCAL INT, @IDGROUP_LOCAL INT, @NAME_LOCAL NVARCHAR(100), @BDAY_LOCAL DATE
FETCH NEXT FROM local_cursor INTO @IDSTUDENT_LOCAL, @IDGROUP_LOCAL, @NAME_LOCAL, @BDAY_LOCAL
PRINT 'Локальный курсор для группы с IDGROUP = 2:'
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT 'ID: ' + CAST(@IDSTUDENT_LOCAL AS NVARCHAR(10)) + ', Группа: ' + CAST(@IDGROUP_LOCAL AS NVARCHAR(10)) + ', Имя: ' + @NAME_LOCAL + ', День рождения: ' + CONVERT(NVARCHAR(10), @BDAY_LOCAL, 104)
    FETCH NEXT FROM local_cursor INTO @IDSTUDENT_LOCAL, @IDGROUP_LOCAL, @NAME_LOCAL, @BDAY_LOCAL
END

CLOSE local_cursor
DEALLOCATE local_cursor
/*3*/
--Static
DECLARE @PUL CHAR(10), @GEN CHAR(2), @NAME1 CHAR(30);
DECLARE TEACHERS CURSOR LOCAL STATIC FOR SELECT PULPIT, GENDER, TEACHER_NAME FROM TEACHER WHERE GENDER='ж';

OPEN TEACHERS;
INSERT INTO TEACHER (TEACHER, TEACHER_NAME, GENDER, PULPIT) VALUES ('НМКВ', 'Немкович Анастасия Вадимовна', 'ж', 'ИСиТ');
UPDATE TEACHER SET TEACHER_NAME = 'Немкович Анастасия Вадимовна' WHERE TEACHER = 'НМКВ';
FETCH TEACHERS INTO @PUL, @GEN, @NAME1;
WHILE @@FETCH_STATUS=0
BEGIN PRINT 'Информация: '+RTRIM(@PUL)+' '+RTRIM(@GEN)+' '+RTRIM(@NAME1);
    FETCH TEACHERS INTO @PUL, @GEN, @NAME1;
END;

CLOSE TEACHERS;
DELETE TEACHER WHERE TEACHER = 'НМКВ';

--Dynamic
DECLARE @PUL_ CHAR(10), @GEN_ CHAR(2), @NAME_ CHAR(30);
DECLARE TEACHERS CURSOR LOCAL DYNAMIC FOR SELECT PULPIT, GENDER, TEACHER_NAME FROM TEACHER WHERE GENDER='ж';

OPEN TEACHERS;
INSERT INTO TEACHER (TEACHER, TEACHER_NAME, GENDER, PULPIT) VALUES ('НМКВ', 'Немкович Анастасия Вадимовна', 'ж', 'ИСиТ');
UPDATE TEACHER SET TEACHER_NAME = 'Немкович Анастасия Вадимовна' WHERE TEACHER = 'НМКВ';
FETCH TEACHERS INTO @PUL_, @GEN_, @NAME_;
WHILE @@FETCH_STATUS=0
BEGIN PRINT 'Информация: '+RTRIM(@PUL_)+' '+RTRIM(@GEN_)+' '+RTRIM(@NAME_);
    FETCH TEACHERS INTO @PUL_, @GEN_, @NAME_;
END;

CLOSE TEACHERS;
DELETE TEACHER WHERE TEACHER = 'НМКВ';

/*4*/
--Разработать сценарий, демон-стрирующий свойства навигации в ре-зультирующем наборе курсора с атри-бутом SCROLL
--Использовать все известные ключе-вые слова в операторе FETCH.
DECLARE @PROFESSION CHAR(20), @FACULTY CHAR(10), @PROFESSION_NAME VARCHAR(100), @QUALIFICATION VARCHAR(50)

DECLARE PROFESSION_CURSOR CURSOR GLOBAL STATIC SCROLL
FOR SELECT PROFESSION, FACULTY, PROFESSION_NAME, QUALIFICATION FROM PROFESSION

OPEN PROFESSION_CURSOR
PRINT 'ВСЕ: '
FETCH PROFESSION_CURSOR INTO @PROFESSION, @FACULTY, @PROFESSION_NAME, @QUALIFICATION
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT '' + @PROFESSION + ' | ' + @FACULTY + ' | ' + @PROFESSION_NAME + ' | ' + @QUALIFICATION
    FETCH PROFESSION_CURSOR INTO @PROFESSION, @FACULTY, @PROFESSION_NAME, @QUALIFICATION
END
CLOSE PROFESSION_CURSOR

OPEN PROFESSION_CURSOR
PRINT 'ПЕРВАЯ СТРОКА: '
FETCH FIRST FROM PROFESSION_CURSOR INTO @PROFESSION, @FACULTY, @PROFESSION_NAME, @QUALIFICATION
PRINT '1' + @PROFESSION + ' | ' + @FACULTY + ' | ' + @PROFESSION_NAME + ' | ' + @QUALIFICATION

PRINT 'ВТОРАЯ СТРОКА (ABSOLUTE): '
FETCH ABSOLUTE 2 FROM PROFESSION_CURSOR INTO @PROFESSION, @FACULTY, @PROFESSION_NAME, @QUALIFICATION
PRINT '2' + @PROFESSION + ' | ' + @FACULTY + ' | ' + @PROFESSION_NAME + ' | ' + @QUALIFICATION

PRINT 'ПЯТАЯ СТРОКА С КОНЦА (ABSOLUTE): '
FETCH ABSOLUTE -5 FROM PROFESSION_CURSOR INTO @PROFESSION, @FACULTY, @PROFESSION_NAME, @QUALIFICATION
PRINT '3' + @PROFESSION + ' | ' + @FACULTY + ' | ' + @PROFESSION_NAME + ' | ' + @QUALIFICATION

PRINT 'ВТОРАЯ СТРОКА (RELATIVE): '
FETCH RELATIVE 2 FROM PROFESSION_CURSOR INTO @PROFESSION, @FACULTY, @PROFESSION_NAME, @QUALIFICATION
PRINT '' + @PROFESSION + ' | ' + @FACULTY + ' | ' + @PROFESSION_NAME + ' | ' + @QUALIFICATION

PRINT 'СЛЕДУЮЩАЯ СТРОКА: '
FETCH NEXT FROM PROFESSION_CURSOR INTO @PROFESSION, @FACULTY, @PROFESSION_NAME, @QUALIFICATION
PRINT '' + @PROFESSION + ' | ' + @FACULTY + ' | ' + @PROFESSION_NAME + ' | ' + @QUALIFICATION

PRINT 'ПОСЛЕДНЯЯ СТРОКА: '
FETCH LAST FROM PROFESSION_CURSOR INTO @PROFESSION, @FACULTY, @PROFESSION_NAME, @QUALIFICATION
PRINT '' + @PROFESSION + ' | ' + @FACULTY + ' | ' + @PROFESSION_NAME + ' | ' + @QUALIFICATION

CLOSE PROFESSION_CURSOR
DEALLOCATE PROFESSION_CURSOR; 


/*5*/
--Создать курсор, демонстрирующий применение конструкции CURRENT OF в секции WHERE с использованием операторов UPDATE и DELETE.
INSERT INTO FACULTY (FACULTY, FACULTY_NAME)
VALUES ('FIRST', 'SECOND');
DECLARE FACULTY_CURSOR CURSOR LOCAL SCROLL DYNAMIC FOR SELECT FACULTY, 
FACULTY_NAME FROM FACULTY FOR UPDATE;
DECLARE @FAC VARCHAR(5), @FULL VARCHAR(50);
OPEN FACULTY_CURSOR
FETCH FIRST FROM FACULTY_CURSOR INTO @FAC, @FULL;
		PRINT @FAC + ' ' + @FULL;
		UPDATE FACULTY SET FACULTY = 'THIRD' WHERE CURRENT OF FACULTY_CURSOR;
		FETCH FIRST FROM FACULTY_CURSOR INTO @FAC, @FULL;
		PRINT @FAC + ' ' + @FULL;
		
	CLOSE FACULTY_CURSOR;
GO
SELECT * FROM FACULTY;

DECLARE faculty_cursor CURSOR FOR
SELECT FACULTY, FACULTY_NAME
FROM FACULTY;
OPEN faculty_cursor;
FETCH NEXT FROM faculty_cursor;
DELETE FROM FACULTY
WHERE CURRENT OF faculty_cursor;
SELECT * FROM FACULTY;
CLOSE faculty_cursor;

/*6*/
--Разработать SELECT-запрос,из таблицы PRO-GRESS удаляются строки, содержащие информацию о студентах, получивших оценки ниже 4.
USE UNIVER;
DECLARE @NOTE INT, @NAME NVARCHAR(50), @FACULTY NVARCHAR(20);
DECLARE Cursor_6 CURSOR DYNAMIC GLOBAL FOR
SELECT PROGRESS.NOTE, STUDENT.NAME, GROUPS.FACULTY
FROM PROGRESS 
JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
OPEN Cursor_6
FETCH Cursor_6 INTO @NOTE, @NAME, @FACULTY
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT 'ОЦЕНКА ' + CAST(@NOTE AS NVARCHAR(10)) + ' - ' + @NAME + ' - ' + @FACULTY
FETCH Cursor_6 INTO @NOTE, @NAME, @FACULTY

IF @NOTE <4
DELETE PROGRESS WHERE CURRENT OF Cursor_6
END
CLOSE Cursor_6

--Разработать SELECT-запрос,в таблице PROGRESS для студента с конкретным номером IDSTUDENT корректируется оценка (увеличивается на единицу).
USE UNIVER;
DECLARE @SUBJECT NVARCHAR(10), @IDSTUDENT INT, @NOTE2 INT
DECLARE TASK6 CURSOR GLOBAL DYNAMIC FOR SELECT SUBJECT, IDSTUDENT, NOTE
FROM PROGRESS FOR UPDATE

OPEN TASK6
FETCH TASK6 INTO @SUBJECT, @IDSTUDENT, @NOTE2
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT @SUBJECT + ' ' +CAST(@IDSTUDENT AS NVARCHAR(10)) + ' ' + CAST(@NOTE2 AS NVARCHAR(20)) 
IF @IDSTUDENT = 1001 UPDATE PROGRESS SET NOTE = NOTE + 1 WHERE CURRENT OF TASK6
FETCH TASK6 INTO @SUBJECT, @IDSTUDENT, @NOTE2
END
CLOSE TASK6
DEALLOCATE TASK6

SELECT SUBJECT[ПРЕДМЕТ], IDSTUDENT[ID СТУДЕНТА], NOTE[ОЦЕНКА] FROM PROGRESS Where SUBJECT = 'ОАиП'
GO

UPDATE PROGRESS SET NOTE = 7 WHERE IDSTUDENT = 1001

