use UNIVER
/*4*/
BEGIN TRANSACTION;
-- t1
INSERT STUDENT (IDGROUP, NAME, BDAY)
VALUES (29, 'Кузнецов Андрей Русланович', '2004-12-01');
-- t2
ROLLBACK;

/*5*/
BEGIN TRANSACTION;
-- t1
INSERT STUDENT (IDGROUP, NAME, BDAY)
VALUES (29, 'Орлова Маргарита Егоровна', '2004-12-08');
-- t2
ROLLBACK;
/*6*/
BEGIN TRANSACTION;
-- t2
INSERT STUDENT (IDGROUP, NAME, BDAY) VALUES (30, 'Киселев Роман Данилович', '2004-09-08');
INSERT  STUDENT (IDGROUP, NAME, BDAY) VALUES (31, 'Воронин Ярослав Арсентьевич', '2004-08-24');
COMMIT;

/*7*/
BEGIN TRANSACTION;
-- t1
DELETE FROM PROGRESS WHERE NOTE = 9;
INSERT PROGRESS VALUES ('СУБД', 1015, '2013-12-01', 10);
UPDATE PROGRESS SET NOTE = 9 WHERE NOTE = 10;
SELECT * FROM PROGRESS WHERE NOTE = 9;
-- t2
SELECT * FROM PROGRESS WHERE NOTE = 9;
COMMIT;
