USE UNIVER
/*1 ROLLUP*/
SELECT
    G.FACULTY, PROFESSION, SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    FACULTY
    JOIN GROUPS G ON FACULTY.FACULTY = G.FACULTY AND G.FACULTY = 'ИДип'
    JOIN STUDENT S ON G.IDGROUP = S.IDGROUP
    JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    ROLLUP (G.FACULTY, PROFESSION, SUBJECT);

/*2 CUBE*/
SELECT
    PROFESSION, SUBJECT, G.FACULTY, AVG(NOTE) AS [Средний балл]
FROM
    FACULTY
    JOIN GROUPS G ON FACULTY.FACULTY = G.FACULTY AND G.FACULTY = 'ИДип'
    JOIN STUDENT S ON G.IDGROUP = S.IDGROUP
    JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    CUBE (G.FACULTY, PROFESSION, SUBJECT);

/*3_1 UNION*/
SELECT
    GROUPS.PROFESSION, P.SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    GROUPS
    FULL JOIN STUDENT S ON GROUPS.IDGROUP = S.IDGROUP AND GROUPS.FACULTY = 'ТОВ'
    FULL JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    P.SUBJECT, GROUPS.PROFESSION

UNION

SELECT
    GROUPS.PROFESSION, P.SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    GROUPS
    FULL JOIN STUDENT S ON GROUPS.IDGROUP = S.IDGROUP AND GROUPS.FACULTY = 'ХТиТ'
    FULL JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    P.SUBJECT, GROUPS.PROFESSION;

/*3_2 UNION ALL*/
SELECT
    GROUPS.PROFESSION, P.SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    GROUPS
    FULL JOIN STUDENT S ON GROUPS.IDGROUP = S.IDGROUP AND GROUPS.FACULTY = 'ТОВ'
    FULL JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    P.SUBJECT, GROUPS.PROFESSION

UNION ALL

SELECT
    GROUPS.PROFESSION, P.SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    GROUPS
    FULL JOIN STUDENT S ON GROUPS.IDGROUP = S.IDGROUP AND GROUPS.FACULTY = 'ХТиТ'
    FULL JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    P.SUBJECT, GROUPS.PROFESSION;

/*4 UNION INTERSECT UNION ALL*/
SELECT
    GROUPS.PROFESSION, P.SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    GROUPS
    FULL JOIN STUDENT S ON GROUPS.IDGROUP = S.IDGROUP AND GROUPS.FACULTY = 'ТОВ'
    FULL JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    P.SUBJECT, GROUPS.PROFESSION

UNION

SELECT
    GROUPS.PROFESSION, P.SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    GROUPS
    FULL JOIN STUDENT S ON GROUPS.IDGROUP = S.IDGROUP AND GROUPS.FACULTY = 'ХТиТ'
    FULL JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    P.SUBJECT, GROUPS.PROFESSION

INTERSECT

SELECT
    GROUPS.PROFESSION, P.SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    GROUPS
    FULL JOIN STUDENT S ON GROUPS.IDGROUP = S.IDGROUP AND GROUPS.FACULTY = 'ТОВ'
    FULL JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    P.SUBJECT, GROUPS.PROFESSION

UNION ALL

SELECT
    GROUPS.PROFESSION,P.SUBJECT, AVG(NOTE) AS [Средний балл]
FROM
    GROUPS
    FULL JOIN STUDENT S ON GROUPS.IDGROUP = S.IDGROUP AND GROUPS.FACULTY = 'ХТиТ'
    FULL JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY
    P.SUBJECT, GROUPS.PROFESSION;

/*5 UNION EXCEPT UNION ALL*/
SELECT 
  GROUPS.PROFESSION,
  PROGRESS.SUBJECT,
  AVG(NOTE) AS [Средний балл]
FROM GROUPS  
  FULL JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP AND GROUPS.FACULTY = 'ТОВ'
  FULL JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY
  PROGRESS.SUBJECT, GROUPS.PROFESSION

UNION

SELECT 
  GROUPS.PROFESSION,
  PROGRESS.SUBJECT,
  AVG(NOTE) AS [Средний балл]
FROM GROUPS 
  FULL JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP AND GROUPS.FACULTY = 'ХТиТ'
  FULL JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY
  PROGRESS.SUBJECT, GROUPS.PROFESSION

EXCEPT

SELECT 
  GROUPS.PROFESSION,
  PROGRESS.SUBJECT,
  AVG(NOTE) AS [Средний балл]
FROM GROUPS  
  FULL JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP AND GROUPS.FACULTY = 'ТОВ'
  FULL JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY
  PROGRESS.SUBJECT, GROUPS.PROFESSION

UNION ALL

SELECT 
  GROUPS.PROFESSION,
  PROGRESS.SUBJECT,
  AVG(NOTE) AS [Средний балл]
FROM GROUPS 
  FULL JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP AND GROUPS.FACULTY = 'ХТиТ'
  FULL JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY
  PROGRESS.SUBJECT, GROUPS.PROFESSION
